# header nav
# 菜单路径
menu:
  home: /
  archives: archives
  tags: tags
  about: about
  friends: friends
  search: search

# site title 
# 页面的标题
# title为空时 Hexo/_config.yml 配置有效
title:

# author profile
# source/imgaes/
# 作者信息
# author为空时 Hexo/_config.yml 配置有效
profile: 
  author:
  avatar: /images/me.jpg  
  description: Call Me PK | 请叫我PK

# site favicon
# source/imgaes/
# 站点图标
favicon: /images/logo160.png

# social link
social:  
  Github: https://github.com/patrick330602
# Weibo:
# Zhihu:
# Facebook:
  Twitter:
  Instagram:
#  LinkedIn:


# toc
# 文章的目录 
toc:
    false

# site analytics 
# 站点访问统计
# [ analytics id ]
baidu_analytics:
google_analytics: 

# comment

# disqus(https://disqus.com/)
disqus:
  comment: false
  shortname: lemonreds

# valine(https://github.com/xCss/Valine)
# 创建 leancloud 应用 获取 id|key 填入即可
leancloud:  
  comment: false
  app_id:
  app_key:

# mob share(http://www.mob.com)
# 文章分享功能
mob_share:
  true

share_item:
- qq
- weixin
- weibo
#- douban
- facebook
- twitter
- tumblr
- google


# donate
# 捐赠功能
# source/imgaes/
donate:
  enable: true
  word: World is nice, and so are you
  wechat: /images/wechatpay.jpg
  alipay: /images/alipay.jpg

# mathjax 
# 渲染LateX公式
# 在post文章头部添加:
#   mathjax: true
# 即可在当前post开启mathjax
mathjax:
  enable: true
  
# excerpt_ignore [boolean]
# increase at the top of your article
# Does this article need to hide the excerpt ?
# 在文章头部中增加此配置 
# 文章是否需要显示摘要 默认为显示

# footer
# 底部信息
footer:
  author: Patrick WU Jinming
  since: 2008


# theme version
#
version:
  0.3.0